DROP DATABASE IF EXISTS NFL_DB;
CREATE DATABASE NFL_DB;

USE NFL_DB;

CREATE TABLE teams (
  id int AUTO_INCREMENT,
  team_name VARCHAR(50) NOT NULL,
  O_rush_YPA DECIMAL(10,1) NULL,
  O_pass_YPA DECIMAL(10,1) NULL,
  D_rush_YPA DECIMAL(10,1) NULL,
  D_pass_YPR DECIMAL(10,1) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE players (

  id INT AUTO_INCREMENT,
  player VARCHAR(50) NOT NULL,
  points INT (10) NOT NUll,
  PRIMARY KEY(id)
);